# Generated by Django 5.1.2 on 2024-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_iscompleted_item_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='#D9D9FF', max_length=7),
        ),
    ]
