# Generated by Django 5.1.2 on 2024-10-30 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_rename_description_item_name_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
